### ISSUE TITLE
Tests for parameter homogeneity

### ISSUE THREAD

**Issue by mariusbarth** [mpt-network/MPTmultiverse#16]
*Participant heterogeneity*. We will assess participant heterogeneity with the asymptotic $\Chi^2$ test as proposed  by  Smith  and  Batchelder  (2008).  Analogously  to  model  fit,  we  will  incorporate  the logarithms of this test’s (frequentist) *p* values  as  a  moderator  into  our  analysis  of  (method-by-method) parameter agreement and, additionally, in our analysis of uncertainty.

**Comment by danheck** [comment]
We will compute this asymptotic test separately for each method (because it is fast) in a new column `test_heterogeneity`.

**Comment by singmann** [comment]
Just to double check. Now the same test is ran for each method? Or am I misunderstanding something and the test somewhat depends on the method as well?

If it is always the same, would it not make sense to have the test in `fit_mpt` instead of in both `mptinr.R` and `treebugs.R` and simply copy it to all rows instead of running it individually for each method? I am not sure how long it takes to run it but if it takes some time, that might give us some speed up.

**Comment by mariusbarth** [comment]
Yes, you are right, the test is run each time one of the methods is invoked. However, reordering the code would only bring negligible speed-up, because the test is quiet quick: e.g., it only takes 3.7 milliseconds for the no-load condition of Beatrice's dataset. So yes, restructuring the code would bring some performance benefits, but this bit is not a bottleneck.

**Comment by singmann** [comment]
I see. I guess we can close this issue then.
